import type { Metadata } from "next";
import Link from "next/link";
import { ArrowRight, Github, Mail, MapPin, ShieldCheck } from "lucide-react";
import { Container } from "@/components/ui/container";
import { Button } from "@/components/ui/button";
import { MarketingNav } from "@/components/marketing/nav";
import { MarketingFooter } from "@/components/marketing/footer";
import { BreadcrumbJsonLd } from "@/components/marketing/json-ld";
import { SITE } from "@/lib/site";

export const metadata: Metadata = {
  title: "About — built by an operator, for operators",
  description: `Why ${SITE.name} exists, who builds it, and what we promise to creators and agencies running real campaigns.`,
  keywords: [
    "ClipFactory founders",
    "AX Studio",
    "independent AI SaaS",
    "EU AI clipping",
    "campaign-first AI clipping",
  ],
  alternates: { canonical: "/about" },
};

const PROMISES = [
  {
    title: "No watermark, ever.",
    body: "Not on Starter, not on any future plan. Your reputation isn't an upsell.",
  },
  {
    title: "Predictable cost.",
    body: "1 minute of source = 1 credit. No revenue share, no surprise overage.",
  },
  {
    title: "Honest scoring.",
    body: "Every clip exposes its 5-axis breakdown. You can disagree with us — and that disagreement tunes the next pick.",
  },
  {
    title: "EU by default.",
    body: "Supabase Frankfurt, Cloudflare R2 EU, Hetzner Germany. No transfer to the US.",
  },
  {
    title: "Cancel in one click.",
    body: "Stripe billing portal, zero friction. No “are you sure” modal cascade.",
  },
  {
    title: "We use what we sell.",
    body: "Every clip you see in the demos was generated by the same pipeline you'll run.",
  },
];

const PRINCIPLES = [
  {
    n: "01",
    title: "Less is more clips that fit.",
    body: "Returning 10 generic clips is easy. Returning 3 clips that match your campaign is the actual job.",
  },
  {
    n: "02",
    title: "Explainable beats magical.",
    body: "Score components, transcripts, segment ranges — everything is in the open. If you can't argue with the AI, you can't improve it.",
  },
  {
    n: "03",
    title: "Cost discipline is product.",
    body: "Vision on candidates only. Cheap models for the map, premium models only where they pay off. The user feels it as price stability.",
  },
  {
    n: "04",
    title: "Ship the boring parts right.",
    body: "Captions burned. EU hosting. Anti-hallucination. Refunds when we fail. Not glamorous, but the difference between a tool and a product.",
  },
];

export default function AboutPage() {
  return (
    <>
      <BreadcrumbJsonLd
        items={[
          { name: "Home", href: "/" },
          { name: "About", href: "/about" },
        ]}
      />
      <MarketingNav />
      <main className="flex-1">
        {/* Intro */}
        <section className="border-b border-[var(--color-border)]">
          <Container className="max-w-3xl py-20">
            <p className="text-xs font-semibold uppercase tracking-wider text-[var(--color-brand)]">
              About
            </p>
            <h1 className="mt-2 text-4xl font-semibold tracking-tight md:text-5xl">
              Clipping built for people who actually run campaigns.
            </h1>
            <div className="mt-10 space-y-6 text-[var(--color-foreground)]">
              <p>
                {SITE.name} started because every AI clipper on the market gives you the same thing:
                ten clips, no context, no campaign awareness, no explanation. You get random viral
                moments — sometimes that works, often it doesn&apos;t.
              </p>
              <p>
                We think clipping should be <strong>campaign-first</strong>. You tell us who you
                talk to, what you sell, what to avoid. Then we pick the clips that fit. Every clip
                ships with a score you can argue with — hook, emotion, visual proof, campaign fit,
                editing difficulty. No black box.
              </p>
              <p>
                On long videos, we go further. We map the whole video first, then look for
                narrative arcs that connect distant moments — a promise made at minute 2, the
                payoff at minute 12, stitched into a single vertical short. That is where the
                algorithm earns its name.
              </p>
            </div>
          </Container>
        </section>

        {/* Principles */}
        <section className="border-b border-[var(--color-border)] bg-[var(--color-muted)]">
          <Container className="max-w-5xl py-20">
            <p className="text-xs font-semibold uppercase tracking-wider text-[var(--color-brand)]">
              How we build
            </p>
            <h2 className="mt-2 text-3xl font-semibold tracking-tight md:text-4xl">
              Four principles we will not compromise.
            </h2>
            <div className="mt-10 grid gap-6 md:grid-cols-2">
              {PRINCIPLES.map((p) => (
                <article
                  key={p.n}
                  className="rounded-lg border border-[var(--color-border)] bg-[var(--color-background)] p-6"
                >
                  <p className="font-mono text-xs text-[var(--color-brand)]">{p.n}</p>
                  <h3 className="mt-2 text-lg font-medium">{p.title}</h3>
                  <p className="mt-2 text-sm text-[var(--color-muted-foreground)]">{p.body}</p>
                </article>
              ))}
            </div>
          </Container>
        </section>

        {/* Promises */}
        <section className="border-b border-[var(--color-border)]">
          <Container className="max-w-5xl py-20">
            <p className="text-xs font-semibold uppercase tracking-wider text-[var(--color-brand)]">
              What we promise
            </p>
            <h2 className="mt-2 text-3xl font-semibold tracking-tight md:text-4xl">
              The fine print, in plain sight.
            </h2>
            <ul className="mt-10 grid gap-4 md:grid-cols-2">
              {PROMISES.map((p) => (
                <li
                  key={p.title}
                  className="rounded-lg border border-[var(--color-border)] p-5"
                >
                  <p className="font-medium">{p.title}</p>
                  <p className="mt-1 text-sm text-[var(--color-muted-foreground)]">{p.body}</p>
                </li>
              ))}
            </ul>
          </Container>
        </section>

        {/* Who builds */}
        <section className="border-b border-[var(--color-border)] bg-[var(--color-muted)]">
          <Container className="max-w-3xl py-20">
            <p className="text-xs font-semibold uppercase tracking-wider text-[var(--color-brand)]">
              Who builds this
            </p>
            <h2 className="mt-2 text-3xl font-semibold tracking-tight md:text-4xl">
              A small team. A deliberate stack.
            </h2>
            <p className="mt-6 text-[var(--color-foreground)]">
              {SITE.name} is built by {SITE.founder} at AX Studio. The product is hosted in the EU
              and runs on a small, deliberate stack: Next.js, FastAPI, asyncpg, Cloudflare R2,
              Supabase, OpenAI Whisper, OpenRouter (DeepSeek + Gemini + Qwen), Anthropic Haiku as
              fallback. No third-party black-box clipping API behind the curtain.
            </p>
            <ul className="mt-8 space-y-2 text-sm text-[var(--color-muted-foreground)]">
              <li className="flex items-center gap-2">
                <MapPin className="h-4 w-4 text-[var(--color-brand)]" /> Hosted in EU regions only.
              </li>
              <li className="flex items-center gap-2">
                <ShieldCheck className="h-4 w-4 text-[var(--color-brand)]" /> GDPR-aware by design — retention windows published.
              </li>
              <li className="flex items-center gap-2">
                <Github className="h-4 w-4 text-[var(--color-brand)]" /> Engineering decisions documented publicly in /docs.
              </li>
            </ul>
          </Container>
        </section>

        {/* Contact CTA */}
        <section>
          <Container className="max-w-3xl py-20 text-center">
            <Mail className="mx-auto h-6 w-6 text-[var(--color-brand)]" />
            <h2 className="mt-4 text-3xl font-semibold tracking-tight md:text-4xl">
              Get in touch.
            </h2>
            <p className="mx-auto mt-3 max-w-xl text-[var(--color-muted-foreground)]">
              Feedback, partnerships, agency volume, press — write to{" "}
              <a className="underline" href={`mailto:${SITE.contactEmail}`}>
                {SITE.contactEmail}
              </a>
              . I read every email myself.
            </p>
            <Link href="/login" className="mt-8 inline-flex">
              <Button size="lg">
                Try ClipFactory
                <ArrowRight className="h-4 w-4" />
              </Button>
            </Link>
          </Container>
        </section>
      </main>
      <MarketingFooter />
    </>
  );
}
